[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "multicalc-suraj"
version = "0.2.5"
description = "A simple calculator library with add, subtract, multiply and divide functions."
readme = "README.md"
requires-python = ">=3.7"
authors = [
    { name="Suraj" }
]

[tool.setuptools]
packages = ["multicalcs"]